openapi: 3.2.0
info:
  title: Dataverse Featured Items API
  description: Open source research data repository software.
  version: '6.9'
servers:
- url: https://dataverse.nl
tags:
- name: DataverseFeaturedItems
paths:
  /dataverseFeaturedItems/{id}:
    put:
      operationId: DataverseFeaturedItems_updateFeaturedItem
      parameters:
      - name: id
        in: path
        required: true
        schema:
          format: int64
          type: integer
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: string
      responses:
        '200':
          description: OK
      tags:
      - DataverseFeaturedItems
    delete:
      operationId: DataverseFeaturedItems_deleteFeaturedItem
      parameters:
      - name: id
        in: path
        required: true
        schema:
          format: int64
          type: integer
      responses:
        '200':
          description: OK
      tags:
      - DataverseFeaturedItems
