openapi: 3.2.0
info:
  title: Dataverse Edit API
  description: Open source research data repository software.
  version: '6.9'
servers:
- url: https://dataverse.nl
tags:
- name: Edit
paths:
  /edit/{fileId}:
    put:
      operationId: EditDDI_edit
      parameters:
      - name: fileId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/xml:
            schema:
              format: binary
              type: string
      responses:
        '200':
          description: OK
      tags:
      - Edit
