openapi: 3.2.0
info:
  title: Dataverse Datasetfields API
  description: Open source research data repository software.
  version: '6.9'
servers:
- url: https://dataverse.nl
tags:
- name: Datasetfields
paths:
  /datasetfields/facetables:
    get:
      operationId: DatasetFields_listAllFacetableDatasetFields
      responses:
        '200':
          description: OK
      tags:
      - Datasetfields
