openapi: 3.2.0
info:
  title: Dataverse Inbox API
  description: Open source research data repository software.
  version: '6.9'
servers:
- url: https://dataverse.nl
tags:
- name: Inbox
paths:
  /inbox:
    post:
      operationId: LDNInbox_acceptMessage
      requestBody:
        content:
          application/ld+json:
            schema:
              type: string
          application/json-ld:
            schema:
              type: string
      responses:
        '200':
          description: OK
      tags:
      - Inbox
