openapi: 3.2.0
info:
  title: Dataverse Add File To Dataset API
  description: Open source research data repository software.
  version: '6.9'
servers:
- url: https://dataverse.nl
tags:
- name: addFileToDataset
  description: Uploads a file for a dataset
paths:
  /datasets/{id}/add:
    post:
      tags:
      - addFileToDataset
      summary: Uploads a file for a dataset
      description: Uploads a file for a dataset
      operationId: Datasets_addFileToDataset
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: string
      responses:
        '200':
          description: File uploaded successfully to dataset
